//
//  WeatherSearch_Protocols.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 28/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WeatherSearch_WireframeProtocol: class {

}
//MARK: Presenter -
protocol WeatherSearch_PresenterProtocol: class {

}

//MARK: Interactor -
protocol WeatherSearch_InteractorProtocol: class {

  var presenter: WeatherSearch_PresenterProtocol?  { get set }
}

//MARK: View -
protocol WeatherSearch_ViewProtocol: class {

  var presenter: WeatherSearch_PresenterProtocol?  { get set }
}
