//
//  WeatherSearch_Presenter.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 28/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherSearch_Presenter: WeatherSearch_PresenterProtocol {

    weak private var view: WeatherSearch_ViewProtocol?
    var interactor: WeatherSearch_InteractorProtocol?
    private let router: WeatherSearch_WireframeProtocol

    init(interface: WeatherSearch_ViewProtocol, interactor: WeatherSearch_InteractorProtocol?, router: WeatherSearch_WireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension WeatherSearch_Presenter{
    
    func startFetchingWeather(query: String) {
        interactor?.fetchForecast(query: query)
    }
    
    func weatherFetchedSuccess(weatherForcast: WeatherForcast) {
        view?.showWeather(weatherForcast: weatherForcast)
    }
    
    func weatherFetchFailed() {
        view?.showError()
    }

}
