//
//  WeatherSearch_Interactor.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 28/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherSearch_Interactor: WeatherSearch_InteractorProtocol {

    weak var presenter: WeatherSearch_PresenterProtocol?
}
