//
//  WeatherSearch_Router.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 28/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherSearch_Router: WeatherSearch_WireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "weathersearchview") as! WeatherSearch_ViewController
        let interactor = WeatherSearch_Interactor()
        let router = WeatherSearch_Router()
        let presenter = WeatherSearch_Presenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
