//
//  WeatherSearch_ViewController.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 28/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherSearch_ViewController: UIViewController, WeatherSearch_ViewProtocol {

	var presenter: WeatherSearch_PresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
