//
//  Homepage_Protocols.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 27/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol Homepage_WireframeProtocol: class {
    func pushToSearchScreen(navigationConroller:UINavigationController)
}
//MARK: Presenter -
protocol Homepage_PresenterProtocol: class {
    func startFetchingWeather()
    func weatherFetchedSuccess(weatherForcast:WeatherForcast)
    func weatherFetchFailed()
}

//MARK: Interactor -
protocol Homepage_InteractorProtocol: class {
    func fetchForecast()
    var presenter: Homepage_PresenterProtocol?  { get set }
}

//MARK: View -
protocol Homepage_ViewProtocol: class {
    func showWeather(weatherForcast:WeatherForcast)
    func showError()
    
    var presenter: Homepage_PresenterProtocol?  { get set }
}
