//
//  Homepage_Interactor.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 27/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Homepage_Interactor: Homepage_InteractorProtocol {

    weak var presenter: Homepage_PresenterProtocol?
}
