//
//  Homepage_Protocols.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 27/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol Homepage_WireframeProtocol: class {

}
//MARK: Presenter -
protocol Homepage_PresenterProtocol: class {

}

//MARK: Interactor -
protocol Homepage_InteractorProtocol: class {

  var presenter: Homepage_PresenterProtocol?  { get set }
}

//MARK: View -
protocol Homepage_ViewProtocol: class {

  var presenter: Homepage_PresenterProtocol?  { get set }
}
