//
//  Homepage_Presenter.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 27/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Homepage_Presenter: Homepage_PresenterProtocol {

    weak private var view: Homepage_ViewProtocol?
    var interactor: Homepage_InteractorProtocol?
    public let router: Homepage_WireframeProtocol

    init(interface: Homepage_ViewProtocol, interactor: Homepage_InteractorProtocol?, router: Homepage_WireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension Homepage_Presenter{
    func startFetchingWeather() {
        interactor?.fetchForecast()
    }
    
    func weatherFetchedSuccess(weatherForcast: WeatherForcast) {
        view?.showWeather(weatherForcast: weatherForcast)
    }
    
    func weatherFetchFailed() {
        view?.showError()
    }
}
