//
//  Homepage_Router.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 27/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Homepage_Router: Homepage_WireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        // let view = Homepage_ViewController(nibName: nil, bundle: nil)
        let view = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "homepageview") as! Homepage_ViewController
        let interactor = Homepage_Interactor()
        let router = Homepage_Router()
        let presenter = Homepage_Presenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
