//
//  Homepage_ViewController.swift
//  iOS-Weather-App
//
//  Created Bridgetech on 27/09/18.
//  Copyright © 2018 Bridgetech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Homepage_ViewController: UIViewController, Homepage_ViewProtocol {

	var presenter: Homepage_PresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
